events {
		worker_connections 1024;
}

http{
	server{
		listen 84;
		location / {
			root /mnt/c/Users/arada/OneDrive/Desktop/Escuela/Quinto_semestre_LISTI/Desarrollo_web/17289/ngnix/3sitios;
			index index.html;
		}
	}
}

