events {
		worker_connections 1024;
}
pid logs/sitio1.pid;
http{
	server{
		listen 83;
		location / {
			root /mnt/c/Users/arada/onedrive/Desktop/Quinto_semestre_LISTI/Desarrollo_Web/17289/nginx/3sitios/sitio3;
			index index.html;
		}
	}
}